[workspace]

[package]
edition = "2024"
name    = "test-app-a"
version = "0.3.0"

[[bin]]
name = "test_duplicate_app"
path = "src/bin/test_duplicate_app.rs"

[[example]]
name = "extras_plugin_duplicate"
path = "examples/extras_plugin_duplicate.rs"

[dependencies]
bevy = { workspace = true, default-features = false, features = [
  "bevy_remote",
] }
bevy_brp_extras = { path = "../extras" }
